// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearTree.Migrations
{
    [DbContext(typeof(GearContext))]
    [Migration("20250916151020_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AmplifierArtist", b =>
                {
                    b.Property<int>("AmplifiersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AmplifiersId", "ArtistsId");

                    b.HasIndex("ArtistsId");

                    b.ToTable("AmplifierArtist");
                });

            modelBuilder.Entity("AmplifierRelation", b =>
                {
                    b.Property<int>("AmplifierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelatedAmplifierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AmplifierId", "RelatedAmplifierId");

                    b.HasIndex("RelatedAmplifierId");

                    b.ToTable("AmplifierRelation");
                });

            modelBuilder.Entity("ArtistGuitar", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuitarsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtistsId", "GuitarsId");

                    b.HasIndex("GuitarsId");

                    b.ToTable("ArtistGuitar");
                });

            modelBuilder.Entity("GearTree.Models.Amplifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GainStructure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTube")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OtherPhotos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerConfiguration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wattage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Amplifiers");
                });

            modelBuilder.Entity("GearTree.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bands")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroPhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OtherPhotos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("GearTree.Models.Guitar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pickups")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Guitars");
                });

            modelBuilder.Entity("GuitarRelation", b =>
                {
                    b.Property<int>("GuitarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelatedGuitarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuitarId", "RelatedGuitarId");

                    b.HasIndex("RelatedGuitarId");

                    b.ToTable("GuitarRelation");
                });

            modelBuilder.Entity("AmplifierArtist", b =>
                {
                    b.HasOne("GearTree.Models.Amplifier", null)
                        .WithMany()
                        .HasForeignKey("AmplifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearTree.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmplifierRelation", b =>
                {
                    b.HasOne("GearTree.Models.Amplifier", null)
                        .WithMany()
                        .HasForeignKey("AmplifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearTree.Models.Amplifier", null)
                        .WithMany()
                        .HasForeignKey("RelatedAmplifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtistGuitar", b =>
                {
                    b.HasOne("GearTree.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearTree.Models.Guitar", null)
                        .WithMany()
                        .HasForeignKey("GuitarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuitarRelation", b =>
                {
                    b.HasOne("GearTree.Models.Guitar", null)
                        .WithMany()
                        .HasForeignKey("GuitarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearTree.Models.Guitar", null)
                        .WithMany()
                        .HasForeignKey("RelatedGuitarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
